# Default values for k8s-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

deploymentAnnotations: {}

containerAnnotations: {}

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

containerPorts:
  http:
    port: 80
    protocol: TCP

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

# We always include a preStop hook with a shutdown delay for eventual consistency reasons.
# See https://blog.gruntwork.io/delaying-shutdown-to-wait-for-pod-deletion-propagation-445f779a8304
shutdownDelay: 5

# Example:
# sideCarContainers:
#   name:
#     image:
#     ...
sideCarContainers: {}

# The minimum number of containers that should be up at any given moment.
minAvailable: 1

service:
  type: ClusterIP
  annotations: {}
  ports:
    http:
      port: 80
      targetPort: http
      protocol: TCP


ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
